// poc_test4_EE_PAYM004-HS_4 - Stack usage check
// M Horn
// November 2015

put() into eol_list

Setup
load_data
load_commands
ssh_handler
conn_handler

// connect to device
Connect_SUT global PAYM_device

// turn on airplane mode
DeviceDriver.setAirplaneMode

wait 30 seconds

// turn off airplane mode, initiate connection to network
DeviceDriver.setAirplaneModeOff

//
// Download 4GB of data
//


(*repeat 4 times
	
	click(FourGB_Image)
	
	-- need to check for 80% & 100% messages as well as redirection to 
	
end repeat*)

// turn on airplane mode
DeviceDriver.setAirplaneMode

//
// Confirm activity in log file
//

// connect to Slate 
put conn_handler.Connect_Slate into log_prodID
put log_procId into global currentProc

// TODO: remove this DEBUG
// confirm we are now 'core' by checking current directory here
ssh_handler.sendSSHInputAndReturn(global cmd_pwd)

// navigate to log directory
ssh_handler.sendSSHInputAndReturn("cd ebdc_core/app_logs")
// extract entries for device under test
set my cmdline to "grep ""<MSISDN>"" ebdc_event_log_*.audit.open > /tmp/epf_logfile_$PPID"
replace "<MSISDN>" by global mobile_number in my cmdline
ssh_handler.sendSSHInputAndReturn( my cmdline)

// search log file for Initiate / Terminate entries
Search_Log global log_GX_Initiate,  "/tmp/epf_logfile_$PPID" -- Gx Initiate

// exit core
ssh_handler.exit_shell

// close SSH session
ssh_handler.close_ssh

// Tear down SUT connection
--Teardown


//


