// poc_test9_EE_PAYM017-HS_4 -EE_PAYM029-BUS_36GB 80% Pass SMS.  verify that 80% SMS is triggered only once in 24 hours for EE PAYM subscribe
// M Horn
// December 2015

Setup
load_data
load_commands
put "http://download.thinkbroadband.com/512MB.zip" into download_url

// connect to device
if status of ConnectionInfo() <> "connected" then
	Conn_Handler.Connect_SUT global device_id
	TypeText homeButton
end if

BeginTestCase POC9_Initial_Disconnect_Subscriber

// turn on airplane mode
DeviceDriver.setAirplaneMode

EndTestCase POC9_Initial_Disconnect_Subscriber

wait 10 seconds

//
// Step 1 - Establish PDP context for EE PAYM subscriber with HS_4GB customer type.
//

BeginTestCase POC9_Establish_PDP_Context

// turn off airplane mode, initiate connection to network
DeviceDriver.setAirplaneModeOff

EndTestCase POC9_Establish_PDP_Context


//
// Step 2 - Exhaust allowance. 80% and 100% usage SMS should be received
//

BeginTestCase POC9_Exhaust_Allowance

// download data until virtual allowance is exhausted
DataTests.BurnData 80, download_url

EndTestCase POC9_Exhaust_Allowance

BeginTestCase POC9_Test_SMS
repeat 5 times
	
	DeviceDriver.setAirplaneMode
	wait 10 seconds
	// turn off airplane mode, initiate connection to network
	DeviceDriver.setAirplaneModeOff
	
	wait 1 minute
	
	if repeatindex() = 1 then -- Step 3 - Disconnect and re-establish PTP session. No Pass SMS should be received
		
		DeviceDriver.openActivityCentre()
		pp_handler.check_for_sms
		
	else --  Step 4 - Disconnect and re-establish context 4 more times. No Pass SMS should not be received again in 24 hour period
		
		DeviceDriver.openMessageList
		
		ScreenUtilities.searchTopQuarter()
		put NumberUtilities.initiatingNumberOnScreen() into threadLocation
		
		if threadLocation equals ()
			ScreenUtilities.searchBottomThreeQuarters()
			put NumberUtilities.initiatingNumberOnScreen() into threadLocation
			if threadLocation equals () then
				Report_Defect "Assertion Failure", "Cannot find matching message thread."
			end if
		end if
		ScreenUtilities.searchBottomHalf()	
		Tap threadLocation
		If not Imagefound(40, Image:"Messaging/Message_Body") then Report_Defect "Image not found", "Unable to find image Messaging/Message_Body"
		
		put DeviceDriver.getLastReceivedMessageBody() into received
		
		replace every occurrence of lf with " " in received.body
		
		if not (received.body contains "80% of data allowance used") then
			Report_Defect "Assertion Failed", format("Expected to receive a message containing: '80% of data allowance used' Received message: '%s'",received.body)
		end if
		
		put item 2 of split(received.body,"SMS") into current_timestamp
		if current_timestamp > global last_message_timestamp then
			logerror "Duplicate 80% SMS received within 24 hours"
		end if
		
	end if
	
	
end repeat

EndTestCase POC9_Test_SMS