// poc_test4_EE_PAYM004-HS_4 - Stack usage check
// M Horn
// November 2015

load_commands
ssh_handler

put() into eol_list

// establish SSH session to Slate
ssh_handler.open_ssh ("testuser", "letmein", "10.249.4.54")
// directory list to ensure we are connected
ssh_handler.sendSSHInputAndReturn(global cmd_ls)

// establish SSH session to OTP
ssh_handler.sendSSHInputAndReturn("ssh adhill@10.249.20.104")
ssh_handler.sendSSHInputAndReturn( "adhill546", ":")

// Note: delimiter is now ">"
insert global defaultSSHendOfLine after eol_list
set global defaultSSHendOfLine to ">"

// directory list to ensure we are connected
ssh_handler.sendSSHInputAndReturn(global cmd_ls)

// su - core
set su_username to "core"
set su_password to "otpus3r."
ssh_handler.su (su_username, su_password)
// confirm we are now 'core' by checking current directory here
ssh_handler.sendSSHInputAndReturn(global cmd_pwd)

// navigate to log directory
ssh_handler.sendSSHInputAndReturn("cd ebdc_core/app_logs")
// extract entries for device under test
set my cmdline to "grep ""<MSISDN>"" ebdc_event_log_*.audit.open > /tmp/epf_logfile_$PPID"
replace "<MSISDN>" by "7432995033" in my cmdline
ssh_handler.sendSSHInputAndReturn( my cmdline)
// search for initialisation strings
ssh_handler.sendSSHInputAndReturn("grep -c ""GX9T"" /tmp/epf_logfile_$PPID")


// exit core
ssh_handler.exit_shell

// restore global defaultSSHendOfLine
set global defaultSSHendOfLine to last item of eol_list
delete last item of eol_list

// close SSH session
ssh_handler.close_ssh